// <auto-generated />
using System;
using Cortside.SqlReportApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cortside.SqlReportApi.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210222231306_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PermissionId");

                    b.Property<int>("ReportGroupId");

                    b.HasKey("ReportId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ReportGroupId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.ReportArgument", b =>
                {
                    b.Property<int>("ReportArgumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArgName");

                    b.Property<string>("ArgType");

                    b.Property<string>("Name");

                    b.Property<int?>("ReportArgumentQueryId");

                    b.Property<int>("ReportId");

                    b.Property<int>("Sequence");

                    b.HasKey("ReportArgumentId");

                    b.HasIndex("ReportArgumentQueryId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportArgument");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.ReportArgumentQuery", b =>
                {
                    b.Property<int>("ReportArgumentQueryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArgQuery");

                    b.HasKey("ReportArgumentQueryId");

                    b.ToTable("ReportArgumentQuery");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.ReportGroup", b =>
                {
                    b.Property<int>("ReportGroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ReportGroupId");

                    b.ToTable("ReportGroup");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.SqlReportApi", b =>
                {
                    b.Property<Guid>("SqlReportApiId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreateSubjectId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<Guid>("LastModifiedSubjectId");

                    b.HasKey("SqlReportApiId");

                    b.HasIndex("CreateSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("SqlReportApi");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.Subject", b =>
                {
                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100);

                    b.Property<string>("GivenName")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(100);

                    b.HasKey("SubjectId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.Report", b =>
                {
                    b.HasOne("Cortside.SqlReportApi.Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cortside.SqlReportApi.Domain.ReportGroup", "ReportGroup")
                        .WithMany()
                        .HasForeignKey("ReportGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.ReportArgument", b =>
                {
                    b.HasOne("Cortside.SqlReportApi.Domain.ReportArgumentQuery", "ReportArgumentQuery")
                        .WithMany()
                        .HasForeignKey("ReportArgumentQueryId");

                    b.HasOne("Cortside.SqlReportApi.Domain.Report")
                        .WithMany("ReportArguments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cortside.SqlReportApi.Domain.SqlReportApi", b =>
                {
                    b.HasOne("Cortside.SqlReportApi.Domain.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreateSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cortside.SqlReportApi.Domain.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
